### ISSUE TITLE
Seed Error Cannot reach any host

### ISSUE THREAD

**Issue by ThomasBush** [algolia/algoliasearch-rails-example#4]
## My Issue
I get an error when trying to run `rake db:seed` command.  Sorry if this is a mistake on my end.  I tried to go through [the rails apps guide](http://railsapps.github.io/openssl-certificate-verify-failed.html) to solving this issue to no avail.  I seem to be up to date on everything they have me check so I am very confused.  I have included the exact error and my versions below.  Please let me know if there is anything else I can provide.

```
Cannot reach any host: SSL_connect returned=1 errno=0 state=SSLv3 read server hello A: sslv3 alert handshake failure, SSL_connect returned=1 errno=0 state=SSLv3 read server hello A: sslv3 alert handshake failure, SSL_connect returned=1 errno=0 state=SSLv3 read server hello A: sslv3 alert handshake failure
```

## My Versions
`openssl version`
OpenSSL 1.0.2a 19 Mar 2015
`ruby -v`
ruby 2.0.0p645 (2015-04-13 revision 50299) [x86_64-darwin14.3.0]
`rails -v`
Rails 4.0.0

I am also using RVM and have gone through the rails apps guide linked above to ensure RVM is at most current version as well as use built in update to certs.

```
$ rvm osx-ssl-certs status all
Certificates for /etc/openssl/cert.pem: Up to date.
Certificates for /usr/local/etc/openssl/cert.pem: Up to date.
```

Thanks for any help you can provide!

**Comment by redox** [comment]
Hi @ThomasBush, I've updated this old sample app to target the latest `algoliasearch-rails` and `algoliasearch` gem; I assume  that was the issue (related to the underlying `httpclient` SSLV3 support). Let me know if that fixes the issue.

**Comment by ThomasBush** [comment]
Thanks @redox !

**Comment by Spone** [comment]
I had the same problem when trying to use `algoliasearch-rails` in a older Rails project.
Adding `gem 'httpclient', '~> 2.6.0.1'` to my Gemfile solved it.

**Comment by redox** [comment]
:+1: @Spone thanks for the follow up.
